### ISSUE TITLE
[Bug] trino-gateway v4 oidc redirecting to http://localhost:8090/sso

### ISSUE THREAD

**Issue by jeffreychucASAPP** [trinodb/trino-gateway#114]
Hi, we originally had oidc to okta working with v3 of trino-gateway with the following config

```
authentication:
 defaultType: oauth
 oauth:
   issuer: ${ISSUER}
   clientId: ${TRINO_GATEWAY_OIDC_CLIENT_ID}
   clientSecret: ${TRINO_GATEWAY_OIDC_CLIENT_SECRET}
   tokenEndpoint: ${ISSUER}/oauth2/v1/token
   authorizationEndpoint: ${ISSUER}/oauth2/v1/authorize
   jwkEndpoint: ${ISSUER}/oauth2/v1/keys
   redirectUrl: https://${URL_OF_GATEWAY}/oidc/callback
   userIdField: email
   scopes:
     - openid
     - email
     - offline_access
```

After we updated to latest version 4 [latest commit of main on trino-gateway at the time]  https://github.com/trinodb/trino-gateway/commit/b6bbb1423f935c36e49e3f2bb83bc44b5336474f when we hit the url of the gateway we had deployed it would redirect to `http://localhost:8090/sso` instead of `http://${URL_OF_GATEWAY}/sso`

I believe the update of `jetty`/`dropwizard` introduced this
https://github.com/trinodb/trino-gateway/commit/434eec9d77465b9373dd07683449102e4d793b83

I tested that theory by checking out the latest v3 and applying all commits one at a time and that was the commit that introduced that behavior.

Hopefully theres just a config option I'm missing but I couldn't get the redirect fixed.
