### ISSUE TITLE
Unable do helm update `trino-gateway-configuration` nil

### ISSUE THREAD

**Issue by Nexengineer** [trinodb/trino-gateway#333]
Hi, 

I am trying to use helm deployment of trino gateway.

trino gateway version: 8

gateway_ovverides.yaml
``` 
# Default values for gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: trinodb/trino-gateway
  pullPolicy: IfNotPresent
  tag: "8"

imagePullSecrets: []

# Provide configuration for the Trino Gateway dataStore in dataStoreSecret. This node can
# be left undefined if dataStore is defined under the config node. For production deployments
# sensitive values should be stored in a Secret
dataStoreSecret:
  name: ''
  key: ''
# Provide configuration for the Trino Gateway backendState in backendStateSecret. This should
# be used with health check configurations that require backend credentials. This node can
# be left undefined if dataStore is defined under the config node.
backendStateSecret:
  name: ''
  key: ''
# Provide configuration for the Trino Gateway authentication configuration in authenticationSecret.
# This node can be left undefined if dataStore is defined under the config node.
authenticationSecret:
  name: ''
  key: ''
config:
  logging:
    type: external
  requestRouter:
    port: 8085
    name: trinoRouter
    historySize: 1000
  server:
    applicationConnectors:
      - type: http
        port: 8090
        useForwardedHeaders: true
    adminConnectors:
      - type: http
        port: 8091
        useForwardedHeaders: true
  clusterStatsConfiguration:
    monitorType: INFO_API
  modules:
    - io.trino.gateway.ha.module.HaGatewayProviderModule
    - io.trino.gateway.ha.module.ClusterStateListenerModule
    - io.trino.gateway.ha.module.ClusterStatsMonitorModule
  managedApps:
    - io.trino.gateway.ha.GatewayManagedApp
    - io.trino.gateway.ha.clustermonitor.ActiveClusterMonitor
  dataStore:
    jdbcUrl: >-
      jdbc:postgresql://local:5432/postgres?currentSchema=master
    user: admin
    password:postgres
    driver: org.postgresql.Driver
service:
  type: ClusterIP
ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 2
    memory: 4Gi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 1
  scheme: HTTP
readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 12
  timeoutSeconds: 1
  scheme: HTTP
volumes: {}
volumeMounts: {}
nodeSelector: {}
tolerations: []
affinity: {}
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ''
```

command :
```
helm upgrade gateway --create-namespace ./trino_gateway/helm/ --install \
          --values trino_gateway/populated/gateway_ovverides.yaml \
          -n trino-gateway
```

error:
```
  Release "gateway" does not exist. Installing it now.
  Error: template: trino-gateway/templates/deployment.yaml:20:71: executing "trino-gateway/templates/deployment.yaml" at <"trino-gateway-configuration">: nil pointer evaluating interface {}.resourceVersion

```
