### ISSUE TITLE
QueryCountBasedRouterProvider Priority vs. Routing Rule

### ISSUE THREAD

**Issue by ndrluis** [trinodb/trino-gateway#487]
Hello,

I activated the `io.trino.gateway.ha.module.QueryCountBasedRouterProvider` and have two routing groups, each with one cluster. 

I also have a rule that directs queries from the "dbt-trino" source to the `large` routing group. However, when I execute multiple queries, some of them are being routed to the `adhoc` routing group. Is this expected behavior, considering that the QueryCount router might have higher priority than the routing rule, or is this a bug?

**Routing Rule**
```yaml
---
name: "dbt"
description: "if query from dbt"
condition: "request.getHeader(\"X-Trino-Source\").startsWith(\"dbt-trino\")"
actions:
  - "result.put(\"routingGroup\", \"large\")"
```

**Clusters**
<img width="486" alt="image" src="https://github.com/user-attachments/assets/cb6b0927-5f94-411d-a398-393c41f1fd26">

**Routing History**
<img width="1482" alt="image (1)" src="https://github.com/user-attachments/assets/095900a4-550c-40d6-83df-4d5711f148ff">
