### ISSUE TITLE
Failure on using dataStoreSecrets

### ISSUE THREAD

**Issue by jasonxu-129** [trinodb/trino-gateway#566]
Hello, I'm trying to deploy Trino Gateway using Helm (version 1.13.0). I have populated the dataStoreSecrets section and removed the dataStore configuration from the config section. However, the final configuration still includes the default values, override/merge from dataStoreSecrets doesn't show up.
```
dataStore:
   driver: org.postgresql.Driver
   jdbcUrl: jdbc:postgresql://localhost:5432/gateway
   password: mysecretpassword
   user: postgres
```
I see code in templates/secrets.yaml
```
data:
    config.yaml: "{{toYaml (merge .Values.config $authenticationDict $dataStoreDict $backendStateDict ) | b64enc}}"
```
I'm not sure how these default values are being populated. Could someone help me understand? Thank you in advance!

**Comment by jasonxu-129** [comment]
@willmostly helped take investigate in slack channel, he find it's due to in
`merge .Values.config $authenticationDict $dataStoreDict $backendStateDict `
.Values.config is populated with the custom values you supply + the default values... which contains 
```
dataStore:
   driver: org.postgresql.Driver
   jdbcUrl: jdbc:postgresql://localhost:5432/gateway
   password: mysecretpassword
   user: postgres
```
the merge function does give precedence to the leftmost dictionary, the default will prevent the value from the secret from taking effect.
