### ISSUE TITLE
Inconsistent OAuth2 authentication failures when accessing Trino clusters through Trino Gateway

### ISSUE THREAD

**Issue by ndrluis** [trinodb/trino-gateway#631]
We have some Trino clusters behind the Trino Gateway. The Trino Clusters login use both PASSWORD and OAUTH authentication. Sometimes when we try to login through the Trino Gateway, we receive the "OAuth2 authentication failed: Authentication response could not be verified" message, and this occurs inconsistently. When we login directly to the Trino Clusters, we never encounter this message.

<img width="451" alt="Image" src="https://github.com/user-attachments/assets/12e3828d-15b0-474c-9da7-948426a2bb83" />

**Comment by jhorlima** [comment]
Hi @ndrluis,

I also experienced the same authentication problem. I ran some tests and based on them, I have come up with a hypothesis that the problem may be related to the way OAuth/OpenID "state" is being handled inside the Trino Gateway. In my view,

-   The "state" is established by a pod (either the Trino Gateway or the Trino AdHoc), and once routed to the external authentication provider (in my case, Google), the callback with the token and state ends up in another pod that does not know the original state established.
-   This unbalanced behavior is what causes the authentication failure with the error message: "OAuth2 authentication failed: Authentication response could not be verified."

I ran the following tests in order to test this hypothesis:

-   **Set the number of Trino Gateway pods to 1**: The problem was still present.
-   **Set the number of Trino AdHoc pods to 1**: The problem disappeared, I tried it 5 times and there were no further failures.

These observations imply that increasing the Trino AdHoc pods might be influencing the authentication process.

To better demonstrate this hypothesis, please see the following sequence diagram:

![Image](https://github.com/user-attachments/assets/fc3076c2-0e17-40e3-a0b6-ac64a347acd4)

As a temporary solution until a permanent one is devised, I suggest reducing the amount of Trino AdHoc pods to 1.

Secondly, I believe a complete solution may be achieved by:

1.  **Sticky sessions**: Configuring the load balancer so that the authentication callback is forwarded to the same pod that initiated the flow.
2.  **Shared state storage**: Utilizing a distributed cache system (e.g., Redis) so that the state generated by one pod is accessible by all pods in the flow.

That said, I would like to know if this hypothesis and these proposals have been considered or if there's another direction planned.

I'm available to help with further tests or to discuss potential implementations.

**Comment by sdaberdaku** [comment]
I am facing a very similar issue. I have two Trino clusters (blue and green) behind Trino Gateway (which is exposed with AWS ALB where the TLS termination is achieved). 
Occasionally I get the OAuth2 authentication failed error. When I start getting the error, the only way to resolve the issue is to clear the cookies on my browser
This is my config:
```yaml
config:
  serverConfig:
    node.environment: production
    http-server.http.port: 8080
    http-server.http.enabled: true
    http-server.process-forwarded: true
  dataStore:
    # -- The connection details for the backend database for Trino Gateway and Trino query history
    jdbcUrl: ${ENV:DB_JDBC_URL}
    user: ${ENV:DB_USERNAME}
    password: ${ENV:DB_PASSWORD}
    driver: org.postgresql.Driver
    queryHistoryHoursRetention: 48
  requestAnalyzerConfig:
    analyzeRequest: true
    tokenUserField: email
  proxyResponseConfiguration:
    responseSize: 128MB
  clusterStatsConfiguration:
    monitorType: INFO_API
#  monitor:
#    connectTimeoutSeconds: 5
#    requestTimeoutSeconds: 10
#    idleTimeoutSeconds: 1
#    retries: 1
  modules: []
  managedApps: []
  gatewayCookieConfiguration:
    enabled: true
    cookieSigningSecret: ${ENV:COOKIE_SIGNING_SECRET}
  oauth2GatewayCookieConfiguration:
    lifetime: 5m
  authentication:
    defaultType: oauth
    oauth:
      issuer: https://accounts.google.com
      clientId: ${ENV:OAUTH2_CLIENT_ID}
      clientSecret: ${ENV:OAUTH2_CLIENT_SECRET}
      tokenEndpoint: https://oauth2.googleapis.com/token
      authorizationEndpoint: https://accounts.google.com/o/oauth2/v2/auth
      jwkEndpoint: https://www.googleapis.com/oauth2/v3/certs
      redirectUrl: https://trino-gateway.example.com/oidc/callback
      redirectWebUrl: https://trino-gateway.example.com/
      userIdField: email
      scopes:
        - openid
        - email
        - profile
  authorization:
    admin: .*ADMIN.*
    user: .*USER.*
    api: .*API.*
  presetUsers:
    sebastian.daberdaku@example.com:
      privileges: ADMIN_USER
```

**Comment by sdaberdaku** [comment]
For those still struggling with this issue, I've momentarily solved it by enabling a routing rule that sends all OAuth2 requests to a given Trino backend cluster in a deterministic way (as described in the documentation).

If you are using the Helm Chart you can achieve this by:
1. Creating a ConfigMap:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: routing-rules
data:
  routing-rules.yaml: |
    ---
    name: "Oauth requests"
    description: "Oauth requests need to go to a single backed"
    condition: "request.getRequestURI.startsWith(\"/oauth2\")"
    actions:
      - "result.put(\"routingGroup\", \"oauth2-handler\")"
```
2. Mounting the ConfigMap as a volume inside your Trino Gateway Pods:
```yaml
# values.yaml
config:
  ...
  gatewayCookieConfiguration:
    enabled: false # don't forget to disable the cookie
  routingRules:
    rulesEngineEnabled: true
    rulesType: FILE
    rulesConfigPath: "/etc/trino-gateway/routing-rules.yaml"
...
volumes:
  - name: routing-rules
    configMap:
      name: routing-rules
      items:
        - key: routing-rules.yaml
          path: routing-rules.yaml

volumeMounts:
  - name: routing-rules
    mountPath: "/etc/trino-gateway/routing-rules.yaml"
    subPath: routing-rules.yaml
```
3. Adding one of your Trino backends as `oauth2-handler` resource group:
<img width="1588" height="448" alt="Image" src="https://github.com/user-attachments/assets/f80d23f9-f8fa-4036-8cb3-f2ef3d5e6273" />
