### ISSUE TITLE
Incorrect Role Assignment in Trino Gateway with OAuth Authentication

### ISSUE THREAD

**Issue by d-gorodnov** [trinodb/trino-gateway#655]
**Description:**
When configuring Trino Gateway with OAuth authentication, users are assigned all possible roles regardless of their specific user configuration in Okta. If the privilegesField is empty for a user, an expected error appears in the logs:
> 2025-03-27T12:03:13.511Z	ERROR	http-worker-242	io.trino.gateway.ha.security.LbAuthenticator	Required privileges field app_role not found

However, when the privilegesField is populated, all users seem to receive every available role, suggesting an issue in how roles are retrieved or processed after fetching user information.

**Steps to Reproduce:**
1. Configure Trino Gateway with the following authentication settings:

```
authentication:
  defaultType: "oauth"
  oauth:
    issuer: ...
    clientId: ...
    clientSecret: ...
    tokenEndpoint: ...
    authorizationEndpoint: ...
    jwkEndpoint: ...
    redirectUrl: ...
    redirectWebUrl: ...
    userIdField: email
    privilegesField: app_role
    scopes:
      - openid
      - email
```

2. Ensure Okta is set up with user roles configured.
3. Attempt to log in as a user with specific roles assigned.
4. Observe that the user receives all possible roles instead of only their assigned ones.

**Expected Behavior:**
Users should only receive the roles explicitly assigned to them in Okta, based on the _privilegesField_ mapping.

**Actual Behavior:**
All users receive all available roles, regardless of their Okta configuration.

**Logs & Screenshots:**

Relevant log output (see error message above). Screenshots of Okta user role configuration.

![Image](https://github.com/user-attachments/assets/39197e46-966e-47af-b86c-31b54f8ea262)
![Image](https://github.com/user-attachments/assets/a90133aa-5eac-464f-8f8e-2fff7f60a29c)

**Comment by oneonestar** [comment]
The role from IDP will be mapped into ADMIN/USER/API through the authorization settings.
You might try something like this:
```
authorization:
  admin: admin
  user: user
  api: api
```
