### ISSUE TITLE
Support credentials specific to each back-end

### ISSUE THREAD

**Issue by naude-r** [trinodb/trino-gateway#66]
in some cases various back-ends may support different credential sets.

it should be possible to override backendState per gateway back-end instance. this should be optional to allow fallback to the global setting.

**Comment by naude-r** [comment]
@willmostly thank you for the response. apologies, suspect my description was unclear. the problem is not with different back-ends for the same cluster, but rather different clusters.

the problem is specific to the following section in the config:
```
backendState:
   username: ${BACKEND_USER}
   password: ${BACKEND_PASSWORD}
   ssl: true
```

from my limited  understanding, it expects the different clusters to be uniform with regards to users and even ssl. if that is the case, is there a way to resolve that? would one still be able to override the Authorization using routing rules?
