### ISSUE TITLE
UI return Login has expired when enable Ldap Authorization

### ISSUE THREAD

**Issue by nqvuong1998** [trinodb/trino-gateway#666]
I set up LDAP authentication and used memberOf as the user attribute. Then, I enabled authorization with the following configuration:
```
authorization:
  admin: (.*)ADMIN(.*)
  user: (.*)USER(.*)
  api: (.*)API(.*)
  ldapConfigPath: /mnt/ldap/ldapConfig.yml
```
However, the UI returns an error: "Login has expired".

After checking the logs, I noticed that: My user was identified as having all roles by default. But my user account does not have the memberOf attribute.
