### ISSUE TITLE
Feature Request: Routing based on number of queued and running queries

### ISSUE THREAD

**Issue by alaturqua** [trinodb/trino-gateway#77]
### Description
Trino Gateway routes queries randomly within a routing group and does not consider the number of already running and queued queries on a cluster within a routing group

### Issue
It can happen that some queries take longer and and queue of the routed cluster keeps growing

#### Example scenario:
Assumption 3 Clusters in a routing group.
- Each cluster receive 50 queries
- cluster 1 and 2 process all the queries and have 0 queries remaining in queued queries
- cluster 3 has received some complex queries and processing needs longer and blocks other queries
- Gateway routes randomly again additional 50 queries to each cluster
- all clusters receive 50 queries to process again
- cluster 3 has 100 queries now, because the one or couple complex queries are in running state and blocking others.

![image](https://github.com/trinodb/trino-gateway/assets/17232317/f55a8610-1555-40ac-a119-501cb6cdb020)
![image](https://github.com/trinodb/trino-gateway/assets/17232317/99949eb5-158f-4fcf-9f40-d318d03df2f9)

### Feature Request
Implement a solution which routes queries based on health status of the backend. It should consider the number of running and queued queries and route new queries to clusters with less load

### Findings on current code
There is already code for this, but it is not used as of now. [ClusterStateListenerModule](https://github.com/trinodb/trino-gateway/blob/main/gateway-ha/src/main/java/io/trino/gateway/ha/module/ClusterStateListenerModule.java#L42-L43) does not have code for it.
https://github.com/trinodb/trino-gateway/blob/main/gateway-ha/src/main/java/io/trino/gateway/ha/router/TrinoQueueLengthRoutingTable.java
https://github.com/trinodb/trino-gateway/blob/main/gateway-ha/src/main/java/io/trino/gateway/ha/clustermonitor/TrinoQueueLengthChecker.java

**Comment by vishalya** [comment]
I can send a PR to try it out, we will need to test out thoroughly.

**Comment by alaturqua** [comment]
I could test it in our dev environment with realistic scenarios.

**Comment by alaturqua** [comment]
I run some tests on the fork/PR in our dev environment.

Tests were done in a realistic scenario using 3x Clusters as trino backend with a routing group named **looker**. Routing rules make sure that every query with source = 'Looker' is routed to routing group **looker**.
```yaml
---
name: "Looker"
description: "Route Looker queries to Looker"
priority: 6
condition: "request.getHeader(\"X-Trino-Source\") contains \"Looker\""
actions:
  - "result.put(\"routingGroup\", \"looker\")"
```

We have set the configs as follows:
```yaml
monitor:
  connectionTimeout: 600
  taskDelayMin: 0.1

modules:
  - io.trino.gateway.ha.module.HaGatewayProviderModule
  - io.trino.gateway.ha.module.ClusterStatsMonitorModule
  - io.trino.gateway.ha.module.QueueLengthListenerModule
  - io.trino.gateway.ha.module.QueueLengthRouterProvider
```

Unfortunately the behavior did not change. We had the same issue like using Random Routing.
As you can see in the screenshot one cluster receives new requests allthough the queue has already 100 queries. And the others have.

Expectation would be that the requests/queries are distributed withing a routing group almost equally.

![image](https://github.com/trinodb/trino-gateway/assets/17232317/fd71d67e-70eb-4049-95ad-c787de760c16)
